#!/bin/sh                                                                                       

PID="com.palm.webosinternals.linphone"
SID="$PID.service"
BIN="linphoneservice"

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Stop the service if running
/sbin/stop ${SID} || true
/usr/bin/killall -9 ${SID} || true

# Remove the service executable
rm -f /var/usr/sbin/${SID}
rm -rf /var/usr/lib/${PID}

# Remove the dbus service
rm -f /var/palm/system-services/${SID}
# Remove the (misnamed) dbus service (happened sometime ago)
# FIXME: remove someday too...
rm -f /var/palm/system-services/${SID}.service

# Remove the ls2 roles
rm -f /var/palm/ls2/roles/prv/${SID}.json
rm -f /var/palm/ls2/roles/pub/${SID}.json

# Remove the upstart script
rm -f /var/palm/event.d/${SID}

# Install the service executable and libraries
mkdir -p /var/usr/sbin/
install -m 755 $APPS/usr/palm/applications/${PID}/bin/${BIN} /var/usr/sbin/${SID}
mkdir -p /var/usr/lib/${PID}
install -m 755 $APPS/usr/palm/applications/${PID}/bin/lib* /var/usr/lib/${PID}/

# Install the dbus service
mkdir -p /var/palm/system-services
cp $APPS/usr/palm/applications/${PID}/dbus/service /var/palm/system-services/${SID}

# Install the ls2 roles
mkdir -p /var/palm/ls2/roles/prv /var/palm/ls2/roles/pub
cp $APPS/usr/palm/applications/${PID}/dbus/json /var/palm/ls2/roles/prv/${SID}.json
cp $APPS/usr/palm/applications/${PID}/dbus/json /var/palm/ls2/roles/pub/${SID}.json
/usr/bin/ls-control scan-services || true

# Install the upstart script
mkdir -p /var/palm/event.d
cp $APPS/usr/palm/applications/${PID}/upstart/script /var/palm/event.d/${SID}

# Start the service
/sbin/start ${SID}

exit 0
