#!/bin/sh

PID="com.palm.webosinternals.linphone"
SID="$PID.service"

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Stop the service
/sbin/stop ${SID} || true
/usr/bin/killall -9 ${SID} || true

# Remove the service executable
rm -f /var/usr/sbin/${SID}
rm -rf /var/usr/lib/${PID}

# Remove the dbus service
rm -f /var/palm/system-services/${SID}
# Remove the (misnamed) dbus service (happened sometime ago)
# FIXME: remove someday too...
rm -f /var/palm/system-services/${SID}.service

# Remove the ls2 roles
rm -f /var/palm/ls2/roles/prv/${SID}.json
rm -f /var/palm/ls2/roles/pub/${SID}.json

# Remove the upstart script
rm -f /var/palm/event.d/${SID}

exit 0
